name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened, auto_merge_enabled]
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r23
      - run: .\build-release.bat
      - uses: actions/upload-artifact@v2
        with:
          name: imagemagick-7-android-static
          path: jniLibs
